version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vote-app
    container_name: vote-app
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  mysql-db:
    image: mysql:8.0
    container_name: voteapp-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
